# fly.toml app configuration file generated for ordernest on 2023-11-07T11:52:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ordernest"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[build]

[[mounts]]
source = "media_volume"
destination = "/app/media"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
